using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;

namespace Funzo.SourceGenerators
{
    [Generator]
    public class ResultGenerator : IIncrementalGenerator
    {
        private const string AttributeName = "ResultAttribute";
        private const string AttributeNamespace = "Funzo";
        private const string AttributeFullName = $"{AttributeNamespace}.{AttributeName}";

        private const string AttributeContent = $@"// <auto-generated />
using System;

#pragma warning disable 1591

namespace {AttributeNamespace}
{{
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class {AttributeName} : Attribute
    {{
    }}
}}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource($"{AttributeName}.g.cs", AttributeContent));

            var resultClasses = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeFullName,
                    IsSyntaxTargetForGeneration,
                    GetSemanticTargetForGeneration)
                .Where(static m => m is not null)
                .Collect();

            context.RegisterSourceOutput(resultClasses, Execute);


            static bool IsSyntaxTargetForGeneration(SyntaxNode node, CancellationToken _)
                => node is ClassDeclarationSyntax classDeclarationSyntax
                       && classDeclarationSyntax.Modifiers.Any(SyntaxKind.PartialKeyword);

            static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
            {
                var symbol = context.TargetSymbol;

                if (symbol is not INamedTypeSymbol namedTypeSymbol)
                {
                    return null;
                }

                var hasAttribute = namedTypeSymbol.GetAttributes().Any(ad =>
                    string.Equals(ad.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), $"global::{AttributeNamespace}.{AttributeName}"));

                return hasAttribute ? namedTypeSymbol : null;
            }
        }

        private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> symbols)
        {
            foreach (var namedTypeSymbol in symbols.Where(symbol => symbol is not null))
            {
                var classSource = ProcessClass(namedTypeSymbol!, context);

                if (classSource is null)
                {
                    continue;
                }

                context.AddSource($"{namedTypeSymbol!.ContainingNamespace}_{namedTypeSymbol.Name}.g.cs", classSource);
            }
        }

        private static string? ProcessClass(INamedTypeSymbol classSymbol, SourceProductionContext context)
        {
            var attributeLocation = classSymbol.Locations.FirstOrDefault() ?? Location.None;

            if (!classSymbol.ContainingSymbol.Equals(classSymbol.ContainingNamespace, SymbolEqualityComparer.Default))
            {
                CreateDiagnosticError(FunzoDiagnosticDescriptors.Result.TopLevelError);
                return null;
            }

            var resultInterfaceType = classSymbol.Interfaces.FirstOrDefault(i => i.Name == "IResult" && i.ContainingNamespace.Name == "Funzo");

            if (classSymbol.BaseType is null || classSymbol.BaseType.Name != "Object" || resultInterfaceType is null)
            {
                CreateDiagnosticError(FunzoDiagnosticDescriptors.Result.WrongBaseType);
                return null;
            }

            var typeArguments = resultInterfaceType.TypeArguments;

            foreach (var typeSymbol in typeArguments)
            {
                if (typeSymbol.Name == nameof(Object))
                {
                    CreateDiagnosticError(FunzoDiagnosticDescriptors.Result.ObjectNotValidType);
                    return null;
                }
            }

            return GenerateClassSource(classSymbol, typeArguments);

            void CreateDiagnosticError(DiagnosticDescriptor descriptor)
            {
                context.ReportDiagnostic(Diagnostic.Create(descriptor, attributeLocation, classSymbol.Name,
                    DiagnosticSeverity.Error));
            }
        }

        private static string GenerateClassSource(INamedTypeSymbol classSymbol, ImmutableArray<ITypeSymbol> typeArguments)
        {
            var isSimpleResult = typeArguments.Length == 1;

            ResultSourceGenerator generator = isSimpleResult
                ? new Result1AritySourceGenerator(classSymbol, typeArguments)
                : new Result2AritySourceGenerator(classSymbol, typeArguments);

            var source = $@"// <auto-generated />

namespace {classSymbol.ContainingNamespace.ToDisplayString()}
{{
    {generator.ClassDefinition}
    {{
        {generator.OkConstructor}
        {generator.OkStaticHelper}
        {generator.OkImplicitConverter}
        {generator.ErrConstructor}
        {generator.ErrStaticHelper}
        {generator.ErrImplicitConverter}
    }}
}}";

            return source;
        }
    }
}
